# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Build And Publish
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.2
        env:
          WELCOME: "Pulling, installing, building"
          LASTSSH: "Copying"
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          first_ssh: |-
            echo $WELCOME
            cd /home/github/nertivia-client-ts
            git pull
            npm install
            npm run build
            ls -la dist
          last_ssh: |-
            echo $LASTSSH &&
            cd /home/github/nertivia-client-ts
            rsync -a dist/ /root/nertivia/public/chatBeta

            
